# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf30b7bf4d230d6d727dd1fdf468692dee202730ceeff131a991cfaf286ffa2440de3084baeeeb403661a37b50f4bd49e08f8c3cac158fc596b7b80290a92a85

test:
  secret_key_base: 8146e76d74c85b3825a413647adca74e109b588a69bffc51218da02f2f8d002a4fcba019e68d4f6954be472a7fac61a797ebe4115259c9e60eb089fbef23a825

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
